### ISSUE TITLE
Unexpected align_assign_span behavior in function member prototype

### ISSUE THREAD

**Issue by chris-mich** [uncrustify/uncrustify#2236]
- Uncrustify-0.68
indent_class = true
align_assign_span = 1

Input
```
class A
{
public:
    virtual void f1( int a, int b, int c ) = 0;
    virtual void f2( int* ptr = nullptr ) = 0;
};
```

Output:
```
class A
{
public:
    virtual void f1( int a, int b, int c ) = 0;
    virtual void f2( int* ptr              = nullptr ) = 0;
};
```

Expected output:
```
class A
{
public:
    virtual void f1( int a, int b, int c ) = 0;
    virtual void f2( int* ptr = nullptr )  = 0;
};
```

I think the sample speaks by itself. :-)

**Comment by arneforlie** [comment]
If you can, please build latest on master, I and think you will find the problem is gone.
(As far as I can see, this was fixed 8 weeks ago with commit 9ff42ee.)

**Comment by chris-mich** [comment]
Issue is still present in uncrustify-0.72, 64-bit Windows version...

**Comment by chris-mich** [comment]
Issue is still present in uncrustify-0.73, 64-bit Windows version...

**Comment by chris-mich** [comment]
Looks good in version 0.74!!  Thank you!

**Comment by Japczy** [comment]
Uncrustify-0.74.0, 64-bit Windows: 
Have same problem
