### ISSUE TITLE
Invalid formatting when the class has a name `interface` in C++

### ISSUE THREAD

**Issue by TheAifam5** [uncrustify/uncrustify#2550]
Version: uncrustify 0.70.0 51f64d6e62f5ea84f2c428c0478d01b1fbf6948c

## Generated results:
main.cpp:
```cpp
#include "sdkconfig.h"

#include <fs/nvs_storage.hpp>
#include <network/interface.hpp>

extern "C" void app_main (void) {
  fs::nvs_storage::initialize ();
  network::interface ::initialize ();
}
```

interface.cpp:
```cpp
#include "sdkconfig.h"
#include "esp_wifi.h"
#include "network/interface.hpp"


using namespace network;
void interface ::initialize () {
  tcpip_adapter_init ();
}
```

## Expected results:
main.cpp:
```cpp
#include "sdkconfig.h"

#include <fs/nvs_storage.hpp>
#include <network/interface.hpp>

extern "C" void app_main (void) {
  fs::nvs_storage::initialize ();
  network::interface::initialize ();
}
```

interface.cpp:
```cpp
#include "sdkconfig.h"
#include "esp_wifi.h"
#include "network/interface.hpp"


using namespace network;

void interface::initialize () {
  tcpip_adapter_init ();
}
```

The new lines between `using namespace network;` and `void interface::initialize () {` are expected. Changing the `interface` to something else, adds the new lines which is what I want.

Currently, Uncrustify adds the space after `interface` and removes the new lines between the `using namespace network;` and `void interface::initialize () {`.

[interface_cpp_debug.txt](https://github.com/uncrustify/uncrustify/files/3886799/interface_cpp_debug.txt)
[main_cpp_debug.txt](https://github.com/uncrustify/uncrustify/files/3886800/main_cpp_debug.txt)
[uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/3886802/uncrustify.cfg.txt)

Regards,
TheAifam5

**Comment by andrey-starodubtsev** [comment]
Was introduced in f3601136.

The gist of the problem: https://stackoverflow.com/questions/25234203/what-is-the-interface-keyword-in-msvc.

Addressed in #2553.

**Comment by TheAifam5** [comment]
I'm gonna check if that fixes my issue :)

**Comment by TheAifam5** [comment]
Hey!
The PR #2553 does not fix the issue completely. 

It fixes following cases:
```cpp
#include "sdkconfig.h"
#include <tcpip_adapter.h>
#include <mutex>

#include "network/interface.hpp"

static std::once_flag m_once;

using namespace espidf::network;
interface ::interface () { // there is still a space
  std::call_once (m_once, []() { tcpip_adapter_init (); });
}

// there is no space between +1
void interface::initializee () {
  tcpip_adapter_init ();
}
```

```
#include "core/application.hpp"
#include "core/provisioner.hpp"

#include "fs/nvs_storage.hpp"

#include "network/interface.hpp"
#include "network/wifi.hpp"
#include "network/ethernet.hpp"

using namespace espidf::core;

application_base::application_base () {
  // there is no space between +1
  network::interface::initializee ();
}

void application_base::reinitialize () {
  finalize ();
  initialize ();
}
```

As you can see, the function calls looks like are fixed, also defining function which is part of the `interface` class, but does not fix the constructor case. The same issue is with defining destructor.

**Comment by andrey-starodubtsev** [comment]
Updated #2553, the fix is a little awkward, but must cover all cases now.

**Comment by TheAifam5** [comment]
I can confirm that #2553 fixes this issue.
Thank you @andrey-starodubtsev !
