### ISSUE TITLE
Wrong indentation of function call arguments when combined with "<<"

### ISSUE THREAD

**Issue by mmichalek-ibl** [uncrustify/uncrustify#4410]
Hello,
arguments inside function call are indented wrongly when `<<` operator is used as well. 2 tabs are used instead of 1 tab. It seems this issue happens when both `indent_continue` and `indent_shift` rules are used at once.

current version: Uncrustify-0.79.0_f

Test file:
```
void foo()
{
	THROW_EXCEPTION(
		"exception reason: %1"
	) << getLastErrorMsg();
}
```

Generated Output:
```
void foo()
{
	THROW_EXCEPTION(
			"exception reason: %1"
		) << getLastErrorMsg();
}
```
Line with `exception reason: %1` is indented wrongly with 2 tabs. It should be indented only with 1 tab. Also line `) << getLastErrorMsg();` is indented wrongly - rule `indent_paren_close` should be applied here.

Expected results:
```
void foo()
{
	THROW_EXCEPTION(
		"exception reason: %1"
	) << getLastErrorMsg();
}
```

Config file:
```
input_tab_size = 4
indent_columns = 4
indent_with_tabs = 2
output_tab_size = 4
indent_paren_close = 2

indent_shift = 1
align_left_shift = false

indent_continue = indent_columns
```

[parsed.txt](https://github.com/user-attachments/files/17798432/parsed.txt)

**Comment by ltomovic-ibl** [comment]
It looks like indent_shift = 1 is causing this. It is interesting that there is a unit test with expected file `30291-indent_shift.cpp` that contains among other things also this
```
    return theAddr.addrN().family() == AF_INET6 ?
        (theAddr.octet(idx * 2) << 8) + theAddr.octet(idx * 2 + 1) :
        theAddr.octet(idx);}
```
which I believe to be wrong. If we replace the shift by multiplication, i.e.
```
    return theAddr.addrN().family() == AF_INET6 ?
              (theAddr.octet(idx * 2) * 8) + theAddr.octet(idx * 2 + 1) :
              theAddr.octet(idx);
```
then it looks like this, it is indented according to the return keyword. However, in case there is a shift, it is all considered as shift expression and then it is indented as the first example. But the shift expression is only this `(theAddr.octet(idx * 2) << 8)`.

Documentation regarding `indent_shift` rule says this
```
# How to indent continued shift expressions ('<<' and '>>').
# Set align_left_shift=false when using this.
#  0: Align shift operators instead of indenting them (default)
#  1: Indent by one level
# -1: Preserve original indentation
indent_shift                    = 0        # number
```
and I believe that this example from unit test is not `continued shift expression`. I mean, continued shift expression is only when one of the operands of the shift expression is on a different line than the shift expression itself. I was playing with it a little and made a [commit](https://github.com/uncrustify/uncrustify/commit/da379fab9e17d2a91c04104f070106cf0a3982da) (in my fork) that modifies this behaviour into something I believe is right.

Can somebody please review this change? Whether it is ok, or not, or what should be changed in order to make a pull request?

**Comment by micheleCTDEAdmin** [comment]
This should now be fixed thanks to PR #4418.

**Comment by ltomovic-ibl** [comment]
Actually, I found a corner case where it still does not work. I was playing with it a little and came with a little bit different implementation that solves also this corner case:

```
	logError("Exception occurred while checking other exception %1\n%2")
		<< std::string(
			reinterpret_cast<const char*>(error.getMessage().data()),
			error.getMessage().size()
		)
```
Here the right operand of shift expression spreads across multiple lines. Implementation in this PR does not take this into account. I improved this and add also unit test for this. I will make another pull request to solve also this corner case.

**Comment by micheleCTDE** [comment]
Sounds good.
